version: '2.0'
services:
  registry:
    image: registry:2
    restart: always
    volumes:
    - ./registry/config.yml:/etc/docker/registry/config.yml
    ports:
    - 5000:5000

  apiserver:
    build: ../server
    depends_on:
    - registry
    ports:
    - 3000:3000
    environment:
      REGISTRY_ENDPOINT: http://registry:5000


  web:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - apiserver
    ports:
    - 80:80




