version: '2.0'
services:
  registry:
    image: registry:2
    restart: always
    volumes:
    - ./registry/config.yml:/etc/docker/registry/config.yml
    - ./registry/local:/var/lib/registry
    ports:
    - 5000:5000

  apiserver:
    build: ../server
    depends_on:
    - registry
    ports:
    - 3000:3000
    environment:
      REGISTRY_ENDPOINT: http://registry:5000


  web:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - apiserver
    restart: always
    ports:
    - 80:80
    # - 8443:8443
    # volumes:
    # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # - ./nginx/fullchain.pem:/etc/nginx/certs/fullchain.pem
    # - ./nginx/privkey.pem:/etc/nginx/certs/privkey.pem

  imgrepos:
    image: minio/minio
    restart: always
    volumes:
    - ./s3-server-cmd.sh:/bin/s3-server-cmd:ro
    environment:
    - MINIO_ACCESS_KEY=__S3_ACCESS_KEY__
    - MINIO_SECRET_KEY=__S3_SECRET_KEY__
    - MINIO_REGION=__S3_REGION__
    network_mode: host
    entrypoint: /bin/s3-server-cmd
