version: '2.0'
services:
  registry:
    image: registry:2
    restart: always
    volumes:
    - ./config.yml:/etc/docker/registry/config.yml
    - ./registry:/var/lib/registry
    ports:
    - 5000:5000

  apiserver:
    build:
      context: ..
      dockerfile: server.Dockerfile
    depends_on:
    - registry
    ports:
    - 3000:3000

  web:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - apiserver
    ports:
    - 80:80




